name: Mystical
version: '${project.version}'
main: mys.serone.mystical.Mystical
api-version: 1.18
authors: [ ItsMystic01 ]
commands:
  fly:
    description: Toggles flight ability
    aliases: [ flight ]
  kit:
    description: Gives the user a kit
    aliases: [ kitme, kits ]
  message:
    description: Messages a user privately
    aliases: [ msg, tell ]
  mysticalhelp:
    description: Shows all the list of commands available
    aliases: [ mysticalcommands ]
  rename:
    description: Rename an item in hand
    aliases: [ itemrename ]
  createkit:
    description: Creates a kit
    aliases: [ ck, kitcreate ]
  deletekit:
    description: Deletes a kit
    aliases: [ dk, kitdelete ]
  setkitprefix:
    description: Sets kit prefix
    aliases: [ skprefix, skitprefix, skp ]
  editkit:
    description: Edit contents of an existing kit
    aliases: [ kitedit ]
  createrank:
    description: Creates a new rank
    aliases: [ newrank, rankcreate ]
  deleteallrank:
    description: Deletes all available ranks in ranks.yml (with optional conditions)
    aliases: [ dar, dallrank ]
  deleterank:
    description: Deletes an existing rank in ranks.yml
    aliases: [ eradicaterank, rankdelete ]
  giverank:
    description: Gives a rank to a certain player
    aliases: [ giverole ]
  playerrank:
    description: Checks the rank a certain player has
    aliases: [ checkplayerrank ]
  ranklist:
    description: Gives all existing ranks
    aliases: [ rankall, allrank, checkallrank ]
  removerank:
    description: Removes a rank from a certain player
    aliases: [ removerole ]
  givepermission:
    description: Gives a user additional permission
    aliases: [ permissionadd ]
  removepermission:
    description: Removes a permission from a user
    aliases: [ permissionremove ]

permissions:
  mystical.*:
    description: Permission over all features of Mystical Plugin.
    default: op
    children:
      mystical.managekits: true
      mystical.roles: true
      mystical.default: true
  mystical.managekits:
    description: Permission over all kits features of Mystical Plugin
    default: false
    children:
      mystical.createkit: true
      mystical.deletekit: true
      mystical.editkit: true
      mystical.setkitprefix: true
  mystical.roles:
    description: Permission over all role features of Mystical Plugin
    default: false
    children:
      mystical.createrank: true
      mystical.deleteallrank: true
      mystical.deleterank: true
      mystical.givepermission: true
      mystical.giverank: true
      mystical.playerrank: true
      mystical.ranklist: true
      mystical.removepermission: true
      mystical.removerank: true
  mystical.default:
    description: Permission over all default features of Mystical Plugin
    default: true
    children:
      mystical.fly: true
      mystical.kit: true
      mystical.message: true
      mystical.help: true
      mystical.rename: true
  mystical.fly:
    description: Permission to enable or disable flight.
    default: true
  mystical.kit:
    description: Ability to claim kits.
    default: true
  mystical.message:
    description: Ability to privately message a user.
    default: true
  mystical.help:
    description: Ability to use the help command of Mystical Commands
    default: true
  mystical.rename:
    description: Ability to rename on-hand item.
    default: true
  mystical.createkit:
    description: Ability to create custom-kits.
    default: op
  mystical.deletekit:
    description: Ability to delete kits from the current custom-kit list.
    default: op
  mystical.editkit:
    description: Ability to edit the contents of a custom-kit.
    default: op
  mystical.setkitprefix:
    description: Ability to change the kit prefix.
    default: op
  mystical.checkallrank:
    description: Ability to check all the current ranks available.
    default: op
  mystical.checkplayerrank:
    description: Ability to check all the rank a user has.
    default: op
  mystical.createrank:
    description: Ability to create a rank.
    default: op
  mystical.deleteallrank:
    description: Ability to delete all current ranks in ranks.yml
    default: op
  mystical.deleterank:
    description: Ability to delete an existing rank.
    default: op
  mystical.givepermission:
    description: Ability to give a user certain permission.
    default: op
  mystical.giverank:
    description: Ability to give a user an existing rank.
    default: op
  mystical.removepermission:
    description: Ability to remove permission from a user.
    default: op
  mystical.removerank:
    description: Ability to remove rank from a user.
    default: op