name: Mystical
version: '${project.version}'
main: mys.serone.mystical.Mystical
api-version: 1.18
authors: [ ItsMystic01 ]
commands:
  fly:
    description: Toggles fly.
    aliases: [ flight ]
  kit:
    description: Gives the user a kit
    aliases: [ kitme ]
  message:
    description: Messages a user privately.
    aliases: [ msg, tell ]
  mysticalHelp:
    description: Shows all the list of commands available.
    aliases: [ mysticalcommands ]
  rename:
    description: Rename an item in hand.
    aliases: [ itemrename ]
  balance:
    description: Shows the balance of the user.
    aliases: [ coins ]
  giveCoins:
    description: Gives coins to a user's balance.
    aliases: [ addbalance ]
  pay:
    description: Pay mentioned user a desired amount within balance.
    aliases: [ expend ]
  removeCoins:
    description: Removes coins from a user's balance.
    aliases: [ removebalance ]
  checkAllRank:
    description: Gives all existing ranks.
    aliases: [ rankall, allrank ]
  checkPlayerRank:
    description: Checks the rank a certain player has.
    aliases: [ playerrank ]
  createRank:
    description: Creates a new rank.
    aliases: [ newrank ]
  deleteRank:
    description: Deletes an existing rank.
    aliases: [ eradicaterank ]
  giveRank:
    description: Gives rank to a certain player.
    aliases: [ giverole ]
  removeRank:
    description: Removes a rank from a certain player.
    aliases: [ removerole ]
  createKit:
    description: Creates a kit.
    aliases: [ ck, kitcreate ]
  deleteKit:
    description: Deletes a kit.
    aliases: [ dk, kitdelete ]
  givePermission:
    description: Gives a user additional permission.
    aliases: [ permissionadd ]
  removePermission:
    description: Removes a permission from a user.
    aliases: [ permissionremove ]