name: Mystical
version: '2.0'
main: mys.serone.mystical.Mystical
api-version: 1.18
authors: [ ItsMystic01 ]
commands:
  fly:
    description: Toggles fly.
    aliases: [ flight ]
  kit:
    description: Gives the user a kit
    aliases: [ kitme ]
  message:
    description: Messages a user privately.
    aliases: [ msg, tell ]
  mysticalHelp:
    description: Shows all the list of commands available.
    aliases: [ mysticalcommands ]
  rename:
    description: Rename an item in hand.
    aliases: [ itemrename ]
  createKit:
    description: Creates a kit.
    aliases: [ ck, kitcreate ]
  deleteKit:
    description: Deletes a kit.
    aliases: [ dk, kitdelete ]
  setKitPrefix:
    description: Sets kit prefix.
    aliases: [ skprefix ]
  editKit:
    description: Edit contents of an existing kit.
    aliases: [ kitedit ]
  checkAllRank:
    description: Gives all existing ranks.
    aliases: [ rankall, allrank ]
  checkPlayerRank:
    description: Checks the rank a certain player has.
    aliases: [ playerrank ]
  createRank:
    description: Creates a new rank.
    aliases: [ newrank ]
  deleteRank:
    description: Deletes an existing rank.
    aliases: [ eradicaterank ]
  giveRank:
    description: Gives rank to a certain player.
    aliases: [ giverole ]
  removeRank:
    description: Removes a rank from a certain player.
    aliases: [ removerole ]
  givePermission:
    description: Gives a user additional permission.
    aliases: [ permissionadd ]
  removePermission:
    description: Removes a permission from a user.
    aliases: [ permissionremove ]
  customParticle:
    description: Creates custom particle.
    aliases: [ cparticle ]
  ping:
    description: Ping
    aliases: [ pings ]

permissions:
  mystical.*:
    description: Permission over all features of Mystical Plugin.
    default: op
    children:
      mystical.managekits: true
      mystical.roles: true
      mystical.default: true
  mystical.managekits:
    description: Permission over all kits features of Mystical Plugin
    default: false
    children:
      mystical.createkit: true
      mystical.deletekit: true
      mystical.editkit: true
      mystical.setkitprefix: true
  mystical.roles:
    description: Permission over all role features of Mystical Plugin
    default: false
    children:
      mystical.checkallrank: true
      mystical.checkplayerrank: true
      mystical.createrank: true
      mystical.deleterank: true
      mystical.givepermission: true
      mystical.giverank: true
      mystical.removepermission: true
      mystical.removerank: true
  mystical.default:
    description: Permission over all default features of Mystical Plugin
    default: true
    children:
      mystical.fly: false
      mystical.kit: true
      mystical.message: true
      mystical.help: true
      mystical.rename: false
  mystical.fly:
    description: Permission to enable or disable flight.
    default: op
  mystical.kit:
    description: Ability to claim kits.
    default: true
  mystical.message:
    description: Ability to privately message a user.
    default: true
  mystical.help:
    description: Ability to use the help command of Mystical Commands
    default: false
  mystical.rename:
    description: Ability to rename on-hand item.
    default: op
  mystical.createkit:
    description: Ability to create custom-kits.
    default: op
  mystical.deletekit:
    description: Ability to delete kits from the current custom-kit list.
    default: op
  mystical.editkit:
    description: Ability to edit the contents of a custom-kit.
    default: op
  mystical.setkitprefix:
    description: Ability to change the kit prefix.
    default: op
  mystical.checkallrank:
    description: Ability to check all the current ranks available.
    default: op
  mystical.checkplayerrank:
    description: Ability to check all the rank a user has.
    default: op
  mystical.createrank:
    description: Ability to create a rank.
    default: op
  mystical.deleterank:
    description: Ability to delete an existing rank.
    default: op
  mystical.givepermission:
    description: Ability to give a user certain permission.
    default: op
  mystical.giverank:
    description: Ability to give a user an existing rank.
    default: op
  mystical.removepermission:
    description: Ability to remove permission from a user.
    default: op
  mystical.removerank:
    description: Ability to remove rank from a user.
    default: op